apiVersion: v1
kind: Service
metadata:
  name: vpa-minallowed-remover
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    app: vpa-minallowed-remover
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8080